// Joan Andrés (@Andres6936) Github.

#ifndef CATACLYSM_MELEHITTYPE_HPP
#define CATACLYSM_MELEHITTYPE_HPP

enum Melee_hit_type
{
	MELEE_HIT_NULL = 0,
	MELEE_HIT_GRAZE,
	MELEE_HIT_NORMAL,
	MELEE_HIT_CRITICAL,
	MELEE_HIT_MAX
};

#endif //CATACLYSM_MELEHITTYPE_HPP
