// Joan Andrés (@Andres6936) Github.

#ifndef CATACLYSM_RANGEDATTACKTYPE_HPP
#define CATACLYSM_RANGEDATTACKTYPE_HPP

enum Ranged_attack_type
{
	RANGED_ATT_NULL = 0,
	RANGED_ATT_THROW,
	RANGED_ATT_FIRE,
	RANGED_ATT_OTHER,
	RANGED_ATT_MAX
};

#endif //CATACLYSM_RANGEDATTACKTYPE_HPP
