// Joan Andrés (@Andres6936) Github.

#ifndef CATACLYSM_HEALTHPOINTSPART_HPP
#define CATACLYSM_HEALTHPOINTSPART_HPP

enum HP_part
{
	HP_PART_NULL = 0,
	HP_PART_HEAD,
	HP_PART_TORSO,
	HP_PART_LEFT_ARM,
	HP_PART_RIGHT_ARM,
	HP_PART_LEFT_LEG,
	HP_PART_RIGHT_LEG,
	HP_PART_MAX
};

#endif //CATACLYSM_HEALTHPOINTSPART_HPP
